version: '3.8'

services:
  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  classroom-compose:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - redis

volumes:
  redis-data:
